---
- name: Check timedatectl status
  hosts: ubuntu
  become: true
  tasks:
    - name: Run timedatectl status
      ansible.builtin.command: timedatectl
      register: timedatectl_status

    - name: Show timedatectl status output
      debug:
        var: timedatectl_status.stdout
