---
- name: Gather all users from the passwd database
  hosts: ubuntu
  gather_facts: true # Ensure facts are gathered, though getent can run without it
  
  tasks:
    - name: Query the passwd database
      # The getent module automatically creates the fact: ansible_facts.getent_passwd
      ansible.builtin.getent:
        database: passwd
      
    - name: Display the list of usernames
      ansible.builtin.debug:
        msg: "Users on {{ inventory_hostname }}: {{ ansible_facts.getent_passwd.keys() | list }}"