---
- name: Ping and Display Destination IP
  hosts: ubuntu_hosts
  gather_facts: false
  
  tasks:
    - name: 1. Execute ICMP Ping to {{ target_ip }}
      ansible.builtin.command:
        # Use the variable in the command
        cmd: "ping -c 5 {{ target_ip }}" 
      register: ping_result

    - name: 2. Display the Ping Destination
      ansible.builtin.debug:
        # 🔑 Access the variable directly in the debug message
        msg: "The destination IP being pinged by {{ inventory_hostname }} is: {{ target_ip }}"

    - name: 3. Display Ping Output
      ansible.builtin.debug:
        msg: "Output: \n{{ ping_result.stdout }}"