---
- name: Ping from Ubuntu Host to a Remote Destination (e.g., 8.8.8.8)
  hosts: ubuntu # You should define this group in your inventory
  gather_facts: false
  
  tasks:
    - name: 1. Execute ICMP Ping to 8.8.8.8 with 5 packets
      ansible.builtin.command:
        # The '-c 5' option limits the count to 5 packets on Linux
        cmd: ping -c 5 8.8.8.8 
      register: ping_result

    - name: 2. Display Ping Results
      ansible.builtin.debug:
        msg: "Ping results from {{ inventory_hostname }}:\n{{ ping_result.stdout }}"